### ISSUE TITLE
这个可以用在多轮的检索式对话系统上吗？

### ISSUE THREAD

**Issue by andrew-begain** [JasonForJoy/MPC-BERT#2]
@JasonForJoy 非常感谢开源您的成果，麻烦问下这个可以用在多轮会话系统上吗？

**Comment by JasonForJoy** [comment]
@andrew-begain 
你好，这个就是应用在多轮对话系统上的。

**Comment by andrew-begain** [comment]
> @andrew-begain 你好，这个就是应用在多轮对话系统上的。

好的，非常感谢
