### ISSUE TITLE
关于用自己的数据集微调的问题

### ISSUE THREAD

**Issue by 935462955** [JasonForJoy/MPC-BERT#3]
请问如果我想用自己的数据集来微调模型并用来处理“回复人识别”任务，请问我的数据集需要如何处理以及处理成什么格式呢？如果可以的话能提供您在论文中使用的“回复人识别”任务的微调数据集给我参考一下吗？另外，如果我想用模型进行预测，是需要自己写代码还是仓库已经提供了呢?

**Comment by JasonForJoy** [comment]
@935462955 
数据集的格式，下载链接以及模型预测脚本都已在本repo下提供，可以仔细阅读readme文件找到对应部分

**Comment by 935462955** [comment]
@JasonForJoy 好的感谢您的回复！

**Comment by 935462955** [comment]
您好，回复人识别任务所预测的结果是“addressee“的索引而不是被回复的那个具体句子的索引（虽然现有的两个数据集有回复关系relation_at，但是默认回复的句子即是addressee最后说的那一句，这似乎并不是很合理。）我本人对深度学习理解不深，所以想请问如果要修改的话您有什么建议吗？

**Comment by JasonForJoy** [comment]
metadata实际上是一组（speaker, utterance, addressee）的序列
relation_at这个标签的来源其实是基于一种启发式的规则，如你所说，“默认回复的句子即是addressee最后说的那一句”。这其实是基于当前数据集，在不做任何额外的人工标注的情况下，成本代价比较小的一种方法。
当然，如果有足够的资源去做人工纠正标注，那当然是一件有利于整个NLP社区的好事。
